### ISSUE TITLE
pip install open ai issuen

### ISSUE THREAD

**Issue by pqingshuang** [Carleslc/AudioToText#2]
ffmpeg version 4.2.7-0ubuntu0.1 Copyright (c) 2000-2022 the FFmpeg developers
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting git+https://github.com/openai/whisper.git@7858aa9c08d98f75575035ecd6481f462d66ca27
  Cloning https://github.com/openai/whisper.git (to revision 7858aa9c08d98f75575035ecd6481f462d66ca27) to /tmp/pip-req-build-vglw1b1g
  Running command git clone --filter=blob:none --quiet https://github.com/openai/whisper.git /tmp/pip-req-build-vglw1b1g
  Running command git rev-parse -q --verify 'sha^7858aa9c08d98f75575035ecd6481f462d66ca27'
  Running command git fetch -q https://github.com/openai/whisper.git 7858aa9c08d98f75575035ecd6481f462d66ca27
  Running command git checkout -q 7858aa9c08d98f75575035ecd6481f462d66ca27
  Resolved https://github.com/openai/whisper.git to commit 7858aa9c08d98f75575035ecd6481f462d66ca27
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in /usr/local/lib/python3.9/dist-packages (1.22.4)
Requirement already satisfied: scipy in /usr/local/lib/python3.9/dist-packages (1.10.1)
Requirement already satisfied: torch in /usr/local/lib/python3.9/dist-packages (1.13.1+cu116)
Collecting deepl
  Using cached deepl-1.14.0-py3-none-any.whl (39 kB)
Collecting pydub
  Using cached pydub-0.25.1-py2.py3-none-any.whl (32 kB)
Collecting openai
  Using cached openai-0.27.1.tar.gz (57 kB)
  Installing build dependencies ... done
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Getting requirements to build wheel ... error
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by Carleslc** [comment]
OpenAI published a new version one hour ago (from 0.27.0 to 0.27.1), probably the error is related to that.

Executing `!pip install --upgrade pip` before the pip install seems to solve the issue. Add that line of code before the last one in the Step 1, or run it in a previous cell.

Another solution is to install the previous working version without upgrading pip, changing `openai` to `openai==0.27.0` in the last line of Step 1.

Before implementing one of those solutions I'll wait a couple of days to see if openai makes some bugfix (new version is still too recent) or if Google Colab upgrades the default pip version.

**Comment by pqingshuang** [comment]
LOL one hour ago im so lucky, anyway i fixed that by the way you mentioned and thanks so much ! you have done a great project !

**Comment by Carleslc** [comment]
Thank you 😊 

I've created a temporal fix in the [`openai-0.27.0`](https://github.com/Carleslc/AudioToText/tree/openai-0.27.0) branch.

[![Open In Colab (openai-0.27.0)](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Carleslc/AudioToText/blob/openai-0.27.0/AudioToText.ipynb)
