### ISSUE TITLE
whisper was not found

### ISSUE THREAD

**Issue by DevLenn** [Carleslc/AudioToText#4]
Hey,
the script installs whisper on it's own, right?

I get the following eeror:
´´´
AudioToText CLI

ffmpeg version 6.1-essentials_build-www.gyan.dev Copyright (c) 2000-2023 the FFmpeg developers
Requirement already satisfied: pip in c:\users\master\appdata\roaming\python\python311\site-packages (23.3.1)
Collecting git+https://github.com/openai/whisper.git@v20230314
  Cloning https://github.com/openai/whisper.git (to revision v20230314) to c:\users\master\appdata\local\temp\pip-req-build-a3g08ciy
  Running command git clone --filter=blob:none --quiet https://github.com/openai/whisper.git 'C:\Users\master\AppData\Local\Temp\pip-req-build-a3g08ciy'
  Running command git checkout -q 6dea21fd7f7253bfe450f1e2512a0fe47ee2d258
  Resolved https://github.com/openai/whisper.git to commit 6dea21fd7f7253bfe450f1e2512a0fe47ee2d258
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy in c:\users\master\anaconda3\lib\site-packages (1.24.3)
Requirement already satisfied: torch in c:\users\master\anaconda3\lib\site-packages (2.1.1)
Requirement already satisfied: deepl in c:\users\master\anaconda3\lib\site-packages (1.16.1)
Requirement already satisfied: pydub in c:\users\master\anaconda3\lib\site-packages (0.25.1)
Requirement already satisfied: openai==0.27.6 in c:\users\master\anaconda3\lib\site-packages (0.27.6)
Requirement already satisfied: requests>=2.20 in c:\users\master\anaconda3\lib\site-packages (from openai==0.27.6) (2.31.0)
Requirement already satisfied: tqdm in c:\users\master\anaconda3\lib\site-packages (from openai==0.27.6) (4.65.0)
Requirement already satisfied: aiohttp in c:\users\master\anaconda3\lib\site-packages (from openai==0.27.6) (3.8.5)
Requirement already satisfied: numba in c:\users\master\anaconda3\lib\site-packages (from openai-whisper==20230314) (0.57.1)
Requirement already satisfied: more-itertools in c:\users\master\anaconda3\lib\site-packages (from openai-whisper==20230314) (8.12.0)
Requirement already satisfied: tiktoken==0.3.1 in c:\users\master\anaconda3\lib\site-packages (from openai-whisper==20230314) (0.3.1)
Requirement already satisfied: ffmpeg-python==0.2.0 in c:\users\master\anaconda3\lib\site-packages (from openai-whisper==20230314) (0.2.0)
Requirement already satisfied: future in c:\users\master\anaconda3\lib\site-packages (from ffmpeg-python==0.2.0->openai-whisper==20230314) (0.18.3)
Requirement already satisfied: regex>=2022.1.18 in c:\users\master\anaconda3\lib\site-packages (from tiktoken==0.3.1->openai-whisper==20230314) (2022.7.9)
Requirement already satisfied: filelock in c:\users\master\anaconda3\lib\site-packages (from torch) (3.9.0)
Requirement already satisfied: typing-extensions in c:\users\master\anaconda3\lib\site-packages (from torch) (4.7.1)
Requirement already satisfied: sympy in c:\users\master\anaconda3\lib\site-packages (from torch) (1.11.1)
Requirement already satisfied: networkx in c:\users\master\anaconda3\lib\site-packages (from torch) (3.1)
Requirement already satisfied: jinja2 in c:\users\master\anaconda3\lib\site-packages (from torch) (3.1.2)
Requirement already satisfied: fsspec in c:\users\master\anaconda3\lib\site-packages (from torch) (2023.4.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\master\anaconda3\lib\site-packages (from requests>=2.20->openai==0.27.6) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\master\anaconda3\lib\site-packages (from requests>=2.20->openai==0.27.6) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\master\anaconda3\lib\site-packages (from requests>=2.20->openai==0.27.6) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\master\anaconda3\lib\site-packages (from requests>=2.20->openai==0.27.6) (2023.7.22)
Requirement already satisfied: attrs>=17.3.0 in c:\users\master\anaconda3\lib\site-packages (from aiohttp->openai==0.27.6) (22.1.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\master\anaconda3\lib\site-packages (from aiohttp->openai==0.27.6) (6.0.2)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in c:\users\master\anaconda3\lib\site-packages (from aiohttp->openai==0.27.6) (4.0.2)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\users\master\anaconda3\lib\site-packages (from aiohttp->openai==0.27.6) (1.8.1)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\master\anaconda3\lib\site-packages (from aiohttp->openai==0.27.6) (1.3.3)
Requirement already satisfied: aiosignal>=1.1.2 in c:\users\master\anaconda3\lib\site-packages (from aiohttp->openai==0.27.6) (1.2.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\master\anaconda3\lib\site-packages (from jinja2->torch) (2.1.1)
Requirement already satisfied: llvmlite<0.41,>=0.40.0dev0 in c:\users\master\anaconda3\lib\site-packages (from numba->openai-whisper==20230314) (0.40.0)
Requirement already satisfied: mpmath>=0.19 in c:\users\master\anaconda3\lib\site-packages (from sympy->torch) (1.3.0)
Requirement already satisfied: colorama in c:\users\master\anaconda3\lib\site-packages (from tqdm->openai==0.27.6) (0.4.6)

Traceback (most recent call last):
  File "D:\DevStuff\RouA\tools\Carleslc-AudioToText-a781256\audiototext.py", line 106, in <module>
    import whisper
ModuleNotFoundError: No module named 'whisper'
´´´

Ty in advance
Lenn

**Comment by DevLenn** [comment]
step 1: install python 3.11, 3.12 won't work
step 2: download & install VC_redist.x64.exe from the official ms page
step 3: run again

**Comment by Carleslc** [comment]
Thank you for posting your solution so others having the same issue can find it.

CLI script installation is here: https://github.com/Carleslc/AudioToText/tree/master#install-audiototext-cli

As stated, Python 3.12 is not supported (whisper codebase supports up to Python 3.11).

**Comment by Carleslc** [comment]
Python 3.12 is now supported with the updated codebase and newer whisper models.
